version: '3.8'

services:
  npm:
    image: node:18
    working_dir: /var/www
    entrypoint: [ "npm" ]
    volumes:
      - ./src:/var/www
  # Web Server Service
  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www
      - ./nginx/conf.d/:/etc/nginx/conf.d/
    depends_on:
      - app
      - db

  #Database Service
  db:
     image : mysql
     container_name : mysql
     volumes:
       - ./mysql/data:/var/lib/mysql
     ports:
       - "3307:3306"
     environment:
       MYSQL_DATABASE: laravel
       MYSQL_ROOT_PASSWORD: 123
  # Application Service
  app:
    container_name: blog
    build: 
      context: ./php
      dockerfile: Dockerfile
    volumes:
      - ./src:/var/www
    ports:
      - "9000:9000"
    working_dir: /var/www

  #phpMyAdmin Service
  phpmyadmin:
     image: phpmyadmin/phpmyadmin
     container_name: phpmyadmin
     ports:
       - "3400:80"
#  pgadmin:
#    image: dpage/pgadmin4
#    container_name: pgAdmin
#    ports:
#      - "5050:80"
#    depends_on:
#      - db
#    environment:
#      PGADMIN_DEFAULT_EMAIL: admin@gmail.com
#      PGADMIN_DEFAULT_PASSWORD: 12345678
